username = "saleh.elnagar@securrency.com"
password = ""
# If you are using Confluence Cloud add the /wiki suffix to base_url
base_url = "https://securrency.atlassian.net/wiki"
h1_title = true
h1_drop = true

space = "SECUR"

parent = [
    "KNOWLEDGE BASE",
    "KB: Architecture",
    "ADR",
]

append_parent = "ADR"

disclaimer = '''
<!-- Macro: :box:([^:]+):([^:]*):(.+):
     Template: ac:box
     Icon: yes
     Name: ${1}
     Title: ${2}
     Body: ${3} -->

<p><ac:structured-macro ac:name="note">
<ac:parameter ac:name="icon">true</ac:parameter>
<ac:parameter ac:name="title">Attention!</ac:parameter>
<ac:rich-text-body>This document is automatically synced by <code>mark</code> tool. <b>All manual changes will be overridden!</b></ac:rich-text-body>
</ac:structured-macro></p>
'''
